version: '3'

services:
    db:
        ports:
            - 5432:5432

    data-collector:
        environment:
            - LOG_LEVEL=DEBUG

    web-app:
        environment:
            - LOG_LEVEL=DEBUG

    nginx:
        ports:
            8080:80